name: Android CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'android/**'
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v4.1.1

      - name: Kotlin Linter
        uses: vroy/gha-kotlin-linter@v4

  build:
    runs-on: macOS-latest
    needs: lint

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
      
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew app:assembleDebug

    - name: Unit tests
      run: ./gradlew testDebugUnitTest

    - name: Run instrumented test
      uses: ReactiveCircus/android-emulator-runner@v2.30.1
      with:
        arch: 'x86_64'
        api-level: 33
        script: ./gradlew app:connectedDebugAndroidTest

    - name: Upload Test Reports Folder
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: reports
        path: |
          app/build/reports
          app/build/test-results

  report:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
    - name: Download Test Reports Folder
      uses: actions/download-artifact@v2
      with:
        name: reports

    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
